import one from "../gallary/one.jpg"
import two from "../gallary/2.jpg"
import three from "../gallary/3.jpg"
import four from "../gallary/4.jpeg"
import five from "../gallary/5.jpg"
import Six from "../gallary/6.jpg"
import Seven from "../gallary/7.jpg"
import eight from "../gallary/8.jpg"
import nine from "../gallary/9.jpg"
import ten from "../gallary/10.jpg"
import eleven from "../gallary/11.jpg"
import twelve from "../gallary/12.jpeg"
import thir10 from "../gallary/13.jpg"
import four10 from "../gallary/14.jpg"
import fif10 from "../gallary/15.jpg"
import six10 from "../gallary/16.jpg"
import Seven10 from "../gallary/17.jpeg"
import eight10 from "../gallary/18.jpeg"
import nine10 from "../gallary/19.jpeg"
import twenty from "../gallary/20.jpeg"
import one20 from "../gallary/21.jpeg"
import two20 from "../gallary/22.jpeg"
import  three20 from "../gallary/23.jpeg"

export let galleryHome =[one,two, three, four,five,Six,Seven,eight,nine,ten,eleven,twelve,thir10,four10,fif10,six10,Seven10,eight10, nine10,twenty,one20,two20,three20]